name: Rodar Robo de Coleta
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests supabase pandas
      - name: Run script
        run: python bot_coleta.py
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
