name: Rodar Robo de Coleta
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v2
      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Instalar dependencias
        run: pip install requests supabase
      - name: Rodar o robo
        run: python bot_coleta.py
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
